# ðŸ•® DiplomaThesis  
By @PHCaesar

image::https://img.shields.io/badge/docs-passing-brightgreen[]

> This project aims to provide a lightweight preconfiguration for the diplomathesis.

Intentionally barebone structure and **docker/asciidoctor** setup.
General structure for Austrian HTL students is provided, other than that you will have to configure all required dependencies, packages and themes yourself.

## Exection

**exec.{bat,bash}**

   # PDF - Quickstart
   generates the pdf file instantly and destroys the container afterwards

**pro-exec.{bat,bash}**

  # Custom Usage 
  creates the docker container and connects you to the container internal prompt

### ðŸªŸ Windows

usage per ðŸ–±ï¸ **DoubleClick** on the bat file

### ðŸ§ Linux (Unix)

[source,bash]
----
# bash [filename]
----

## Requirements
* [x] Docker installed
* [x] Diploma project

## Tipps
> For perfect usage you will have to include a gitmodule / reference to your actual diploma project

*Recommended Dependencies :*

- https://docs.asciidoctor.org/diagram-extension/latest/[asciidoctor-diagram]


# Examples :
- **2023** - https://github.com/3D-printing-Web-interface/DiplomaThesis-Lithoz-3D-Printing-WebInterface[3D_printing_web_interface]
